AY2223S2-CS2103T-W11-3/tp

docs/team/ruiyigan.md
=> Add ruiyigan PPP

docs/team/unfazing.md
Added skeletal markdown file for PPP
=> Add skeletal PPP

src/main/java/seedu/address/model/powercard/Answer.java, src/main/java/seedu/address/model/powercard/Powercard.java, src/main/java/seedu/address/model/powercard/Question.java
**Issues handled**
Closes #8
**Remarks**
- I mainly followed how they implemented Person class, left Person class there for future references as AB3 also has tag functionality which may be useful later on. Removed extra methods that we don't need at the moment.
- I think you can take reference from Addressbook class. May be quite relevant.
**Completed**
**Future Issues (if any)**
- Testing for Powercard, Question, and Answer Class #27 #26 
- Potential conflict with #10
=> Create Powercard Class

README.md
=> Update README UI description

src/main/java/seedu/address/model/powercard/PowerCard.java, src/main/java/seedu/address/model/powercard/UniqueCardList.java, src/main/java/seedu/address/model/powerdeck/PowerDeck.java, src/main/java/seedu/address/model/powerdeck/ReadOnlyPowerDeck.java
Closes #10 
- I mostly followed the AddressBook implementation for the PowerCard. 
- Test cases for PowerDeck class
=> Add PowerDeck class, addCard and removeCard methods

src/main/java/seedu/address/model/CardModel.java, src/main/java/seedu/address/model/CardModelManager.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/powercard/UniqueCardList.java, src/main/java/seedu/address/model/powerdeck/PowerDeck.java, src/test/java/seedu/address/model/CardModelManagerTest.java, src/test/java/seedu/address/model/powerdeck/PowerDeckTest.java
My bad. I should have merged your changes directly to master then branching out. Instead of branching out then merging.
=> Add model class

src/main/java/seedu/address/model/DeckModel.java, src/main/java/seedu/address/model/DeckModelManager.java, src/test/java/seedu/address/model/DeckModelManagerTest.java
**Issue addressed:** 
#40
**Details:**
Edited on top of @rockman007372 changes. Added measures and attributes to support multiple decks.
Create some default cards and decks to be used for test cases
=> Add new methods to support multiple decks

src/main/java/seedu/address/logic/commands/Command.java, src/main/java/seedu/address/logic/commands/deckcommands/SelectDeckCommand.java, src/main/java/seedu/address/model/DeckModel.java, src/main/java/seedu/address/model/DeckModelManager.java, src/main/java/seedu/address/model/powerdeck/PowerDeck.java, src/main/java/seedu/address/model/util/SampleCardUtil.java
I made various tweaks to the code and add a few classes:
- Add SelectDeckCommand.
- Add SampleCardUtil (sample cards to add to deck if no save files found).
- Tweak and organise Deck methods inside DeckManager.
Issue addressed: #48
=> Add SelectDeckCommand and various tweaks

src/main/java/seedu/address/logic/Logic.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/AddDeckCommand.java, src/main/java/seedu/address/logic/commands/ClearCommand.java, src/main/java/seedu/address/logic/commands/SelectDeckCommand.java, src/main/java/seedu/address/logic/parser/SelectDeckCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/ui/MainWindow.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/ClearCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/commands/ListCommandTest.java, src/test/java/seedu/address/model/ModelManagerTest.java
Made some minor changes so that the command can be tested in GUI. 
- update import statements
- update javadoc
Note when testing the command, a data file is created. If you try to run the programme again with the data file, it results in a null error due to Storage being unable to parse the current json. Todo in future.
Addresses #48
=> Complete SelectDeckCommand

src/main/java/seedu/address/logic/commands/UnselectDeckCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/model/ModelManager.java
Allow user to unselect deck by setting selectedDeck in Model as null.
Closes #70
=> Add UnselectDeck command

src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/parser/MasterDeckParser.java, src/main/java/seedu/address/storage/JsonAdaptedCard.java, src/main/java/seedu/address/storage/JsonSerializableAddressBook.java, src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json, src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/logic/parser/MasterDeckParserTest.java, src/test/java/seedu/address/storage/JsonAdaptedCardTest.java
- Rename AddressBook to MasterDeck Parser
- Refactor JsonAdaptedPerson to JsonAdaptedCard
- Rename sample data name -> question address -> answer
=> Remove some traces of Address Book 

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/EndReviewCommand.java, src/main/java/seedu/address/logic/commands/FlipCommand.java, src/main/java/seedu/address/logic/commands/ReviewCommand.java, src/main/java/seedu/address/logic/commands/SelectDeckCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/ReviewCommandParser.java, src/main/java/seedu/address/model/MasterDeck.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/card/Card.java, src/main/java/seedu/address/model/card/CardInDeckPredicate.java, src/main/java/seedu/address/model/review/Review.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/ui/PersonCard.java, src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/storage/JsonAdaptedCardTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/PersonUtil.java, src/test/java/seedu/address/testutil/TypicalPersons.java
- Added ReviewCommand, EndReviewCommand, FlipCommand and parsers where nec. 
- Added a Review class to models.
- Added a CardInDeckPredicate to get the filtered list of cards in the specified deck.
- Implemented logic for the commands
- Updated test cases to support List of Decks (see initDecks() in MasterDeck class).
Currently model holds a Review object called currReview. This current review will store all the information necessary to generate user performance statistics (to be implemented in future). Note a user can start a review anytime (whether or not a deck is selected). Once the user is in a review session, they must end the review it before starting another one.
Addresses #43
=> Add Functionality for Review 

docs/diagrams/tracing/LogicSequenceDiagram.puml, docs/tutorials/TracingCode.md, src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/MasterDeckParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java, src/test/java/seedu/address/logic/commands/EditCardDescriptorTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/commands/FindCommandTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/logic/parser/MasterDeckParserTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonUtil.java
**Issues handled**
Closes #74 and #75 
**Completed**
=> Enable Edit and Delete card command when deck selected

src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/AddDeckCommand.java, src/main/java/seedu/address/logic/commands/EditDeckCommand.java, src/main/java/seedu/address/logic/commands/ExitCommand.java, src/main/java/seedu/address/logic/parser/EditDeckCommandParser.java, src/main/java/seedu/address/logic/parser/MasterDeckParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java
As a user I can edit the name of a deck
Edit the name name of the deck followed by its indeck and new name
#83
=> Add editDeck command

src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Load the decks from JSON.
Implementation: 
- Add the deck of each card if the deck is not already in the deckList.
=> Enable Storage to load the decks from JSON file

src/main/java/seedu/address/ui/DeckListPanel.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/PersonListPanel.java, src/main/resources/view/Extensions.css, src/main/resources/view/MainWindow.fxml, src/main/resources/view/PersonListCard.fxml, src/main/resources/view/Theme.css
Theme has been further updated with changes to the commandbox, display and padding on both deck and card list. Border on commandbox still needs to be removed! ( I wasn't able to locate the code responsible for it)
=> Theme update

src/main/java/seedu/address/logic/parser/MasterDeckParser.java
=> Skip unselectDeck when selecting new deck

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/storage/JsonAdaptedCard.java, src/main/java/seedu/address/storage/JsonMasterDeckStorage.java, src/main/java/seedu/address/storage/JsonSerializableMasterDeck.java, src/main/java/seedu/address/storage/MasterDeckStorage.java, src/main/java/seedu/address/storage/Storage.java, src/main/java/seedu/address/storage/StorageManager.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/storage/JsonMasterDeckStorageTest.java, src/test/java/seedu/address/storage/StorageManagerTest.java
#127 
Convert most instances of addressbook to masterdeck in the Storage classes.
=> Refractor storage class to remove traces of AddressBook

src/main/java/seedu/address/logic/commands/DeleteDeckCommand.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/deck/Deck.java, src/test/java/seedu/address/logic/commands/AddDeckCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteDeckCommandTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/commands/EditDeckCommandTest.java, src/test/java/seedu/address/logic/commands/ListCommandTest.java, src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/testutil/TypicalDecks.java, src/test/java/seedu/address/testutil/TypicalIndexes.java
=> Add test cases for deck commands

src/main/resources/view/DeckListPanel.fxml, src/main/resources/view/PersonListPanel.fxml, src/main/resources/view/Theme.css
Outer containers are now padded.
=> Round out corner

src/main/java/seedu/address/logic/commands/EditDeckCommand.java, src/main/java/seedu/address/logic/parser/EditDeckCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/deck/Deck.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/DeleteDeckCommandTest.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/AddDeckCommandParserTest.java, src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java, src/test/java/seedu/address/logic/parser/DeleteDeckCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditDeckCommandParserTest.java
=> Test cases for Deck Command Parser

src/main/java/seedu/address/logic/Logic.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/CommandResult.java, src/main/java/seedu/address/logic/commands/EndReviewCommand.java, src/main/java/seedu/address/logic/commands/ExitCommand.java, src/main/java/seedu/address/logic/commands/HelpCommand.java, src/main/java/seedu/address/logic/commands/ReviewCommand.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/review/Review.java, src/main/java/seedu/address/ui/DeckListPanel.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/ReviewStatsPanel.java, src/main/resources/view/MainWindow.fxml, src/main/resources/view/ReviewStatsPanel.fxml, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/AddDeckCommandTest.java, src/test/java/seedu/address/logic/commands/CommandResultTest.java, src/test/java/seedu/address/logic/commands/ExitCommandTest.java, src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Created new ReviewStatsPanel component and implemented logic to display updated review stats (deck name, current card number, current score) at the left panel.
Needs styling but is functional
Notes:
- refactored the deckListPanel to leftPanel.
- the leftPanel will show the ReviewStatsPanel during a review and will show the DeckListPanel when not in a review.
- uses booleans in CommandResult to update the UI
closes #153
=>  Review sidebar containing review statistics

src/main/java/seedu/address/logic/commands/CommandResult.java, src/main/java/seedu/address/logic/commands/EndReviewCommand.java, src/main/java/seedu/address/logic/commands/ExitCommand.java, src/main/java/seedu/address/logic/commands/HelpCommand.java, src/main/java/seedu/address/logic/commands/ReviewCommand.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/review/Review.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/java/seedu/address/ui/PersonListPanel.java, src/main/java/seedu/address/ui/ReviewCard.java, src/main/resources/view/ReviewCard.fxml, src/test/java/seedu/address/logic/commands/CommandResultTest.java, src/test/java/seedu/address/logic/commands/ExitCommandTest.java, src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Future issue: Reformat the review card to look like UI mockup.
Close #152
=> [GUI] Separate Index From Card during Review

docs/UserGuide.md
#107 
Add more features and update the UG
(Re-open due to the codecov error)
=> Update UserGuide.md (new pr)

src/main/java/seedu/address/ui/PersonCard.java, src/main/java/seedu/address/ui/ReviewCard.java, src/main/resources/view/PersonListCard.fxml, src/main/resources/view/ReviewCard.fxml, src/main/resources/view/Theme.css
=> Make questions and answer more distinct + centralise card fields

src/main/java/seedu/address/logic/commands/TagCardDuringReviewCommand.java, src/main/java/seedu/address/logic/parser/MasterDeckParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/logic/parser/TagCardDuringReviewCommandParser.java, src/main/java/seedu/address/model/MasterDeck.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/card/Card.java, src/main/java/seedu/address/model/card/UniqueCardList.java, src/main/java/seedu/address/model/review/Review.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/AddDeckCommandTest.java
Closes #106.
Only can be used after you flip the card. 
Only accepts Easy, Medium, Hard tags (Non case sensitive and ok with white spaces ie `      easy` also valid.
**Issues**
- Card not automatically updated with tag at the moment. Ie: after I tag the card with medium the card won't display the new tag immediately. To be discussed with @junianob. (see below)
- Add test cases once feature is approved.
Is it cause the feature is not using an observable list? Not too sure... 
https://user-images.githubusercontent.com/85063215/226331233-0235bb0f-d0b5-4a12-b65c-ea50c571568d.mov
=> Branch tag during review

src/main/resources/view/ReviewCard.fxml
=> Update ReviewCard.fxml to centralise Answer field in GUI under Review

src/main/java/seedu/address/logic/commands/reviewcommands/FlipCardCommand.java, src/main/java/seedu/address/logic/commands/reviewcommands/MarkCorrectCommand.java, src/main/java/seedu/address/logic/commands/reviewcommands/MarkWrongCommand.java, src/main/java/seedu/address/logic/commands/reviewcommands/NextCardCommand.java, src/main/java/seedu/address/logic/commands/reviewcommands/PreviousCardCommand.java, src/main/java/seedu/address/model/review/Review.java, src/main/java/seedu/address/ui/MainWindow.java
Now the commands for review are as follows:
Previous: [
Next: ]
Flip: \\
Mark Wrong: ;
Mark Correct: '
For ease of understanding as "[" and "]" representing prev and next is more intuitive than before.
=> Amend user commands for Review and add NavGuide to sidebar

src/main/java/seedu/address/ui/FlippedReviewCard.java, src/main/java/seedu/address/ui/PersonListPanel.java, src/main/java/seedu/address/ui/UnflippedReviewCard.java, src/main/resources/view/FlippedReviewCard.fxml, src/main/resources/view/Theme.css, src/main/resources/view/unflippedReviewCard.fxml
Now the colour of a card under review is purple. When flipped, it is light purple.
Colours can be changed in the Themes.css file.
Unflipped:
Flipped:
addresses #151
=> Add different colours for card under review

src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/logic/parser/MasterDeckParser.java, src/main/java/seedu/address/model/deck/DeckContainsKeywordsPredicate.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/FindCommandTest.java, src/test/java/seedu/address/logic/parser/FindCommandParserTest.java, src/test/java/seedu/address/logic/parser/MasterDeckParserTest.java, src/test/java/seedu/address/model/deck/DeckContainsKeywordsPredicateTest.java
Closes #192 
When deck is not selected, find command filters the deck section
When deck is selected, find command filters the card section
https://user-images.githubusercontent.com/85063215/227448272-c02a29e3-2cb9-4207-a986-ee5211e3367e.mov
=> Tweak find command functionality based on modes

src/main/java/seedu/address/logic/Logic.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/cardcommands/AddCommand.java, src/main/java/seedu/address/logic/commands/deckcommands/UnselectDeckCommand.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/ui/DeckName.java, src/main/java/seedu/address/ui/DeckNamePanel.java, src/main/java/seedu/address/ui/MainWindow.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/ListCommandTest.java, src/test/java/seedu/address/logic/commands/cardcommands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/cardcommands/DeleteCommandTest.java, src/test/java/seedu/address/logic/commands/cardcommands/EditCommandTest.java, src/test/java/seedu/address/logic/commands/deckcommands/AddDeckCommandTest.java, src/test/java/seedu/address/model/ModelManagerTest.java
https://user-images.githubusercontent.com/80334013/227694901-669442c7-708a-4f87-9f59-7564c97dbaef.mp4
Other changes:
- Right title panel will no longer take in `ObservableList<Pair<...>>` to prevent type warning. It will take in `ObservableList<String>` instead. I made use of the already available Model::getSelectedDeckName for this.
=> [GUI] Main Mode will not show any cards, until a deck is selected.

src/main/java/seedu/address/ui/MainWindow.java
=> Fix bug in End Review mode

src/main/java/seedu/address/logic/commands/reviewcommands/ReviewCommand.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/logic/parser/ReviewCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/card/CardHasTagPredicate.java, src/main/resources/view/MainWindow.fxml, src/test/java/seedu/address/model/ModelStub.java
Users can now Review specific difficulties of cards in a deck.
**Usage** 
`review 1`  - reviews all cards in deck with index 1
`review 1 e\` - reviews all cards tagged easy in deck with index 1
`review 1 e\ h\` - reviews all cards tagged easy and hard in deck with index 1
Created a new CardHasTag predicate that is filtered before the Review is created. 
close #210
=> Feature - allow users to review by tag

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/reviewcommands/SetReviewLimitCommand.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/logic/parser/SetReviewLimitCommandParser.java, src/main/resources/view/Theme.css, src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Added user guide sections:
- Command Summary
- Main Mode after selecting deck
- Review Mode
=> User Guide

src/main/java/seedu/address/ui/MainWindow.java
- Can have leading whitespace in keywords
- Keywords reset after every Find command
=> Update MainWindow.java to fix bug 

src/main/java/seedu/address/logic/commands/cardcommands/AddCardCommand.java, src/main/java/seedu/address/logic/commands/cardcommands/EditCardCommand.java, src/main/java/seedu/address/model/deck/Deck.java, src/main/java/seedu/address/ui/HelpWindow.java
- addDeck message
- addCard message
- editCard message
- Fix wrong link
Closes #264 #273 #292 #294 #295
=> Fix some error message bugs

src/main/java/seedu/address/logic/commands/reviewcommands/ReviewCommand.java
error message now displays invalid deck index #283
=> Fix Review Error Message

src/main/java/seedu/address/logic/commands/ClearCommand.java
=> Fix Grammar issue in clear command message

docs/UserGuide.md
=> Update User Guide to include case insensitivity

docs/UserGuide.md
- close #278 
- close #274 
- Informs user that they can use SelectDeck anywhere in Main Mode
- close #268 
- close #265 
- close #263
=> Fix the remaining issues in UG

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/reviewcommands/SetReviewLimitCommand.java, src/main/java/seedu/address/logic/parser/ParserUtil.java
=> Add limit description to specify the acceptable range of limit

src/main/resources/view/MainWindow.fxml
Closes #293. Prof gave the green light on teams.
Can test it on your end.
=> Fix max screen when launch

src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ReviewCommandParser.java
Flags for review command are now case insensitive. Not very elegant but this is the best solution given the implementation. Closes #275
=> Fix review flag case insensitive

src/main/java/seedu/address/logic/parser/MasterDeckParser.java
=> Make review command case insensitive

docs/UserGuide.md
Im trying to fix the bug below:
=> Fix UG minor bug

src/test/data/JsonSerializableMasterDeckTest/typicalCardsMasterDeck.json, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/reviewcommands/TagEasyCommandTest.java, src/test/java/seedu/address/logic/commands/reviewcommands/TagHardCommandTest.java, src/test/java/seedu/address/logic/commands/reviewcommands/TagMediumCommandTest.java, src/test/java/seedu/address/logic/parser/FindCardsCommandParserTest.java, src/test/java/seedu/address/logic/parser/FindDecksCommandParserTest.java, src/test/java/seedu/address/logic/parser/ReviewCommandParserTest.java, src/test/java/seedu/address/logic/parser/SelectDeckCommandParserTest.java, src/test/java/seedu/address/logic/parser/SetReviewLimitCommandParserTest.java, src/test/java/seedu/address/testutil/TypicalCards.java, src/test/java/seedu/address/testutil/TypicalIndexes.java
Add testcases to the following classes
**Parser**
- FindCards
- SelectDeck
- SetReviewLimit
- Review
**Logic**
- LogicManager
**Command**
- TagEasy
- TagMedium
- TagHard
=> Code coverage Bump

src/main/java/seedu/address/logic/commands/deckcommands/EditDeckCommand.java
Change the format same as in UG
DECK NAME into DECK_NAME in the editDeck error message
Closes #287
=> Unify format of DECK_NAME

src/main/java/seedu/address/ui/MainWindow.java
There is now a logo in the clear window. closes #282
=> Add logo for clear window

docs/DeveloperGuide.md
- Enlarge the size of Model class diagram
- Fix bug where the Alert box takes up the whole DG
=> Update DeveloperGuide to fix bugs

docs/UserGuide.md
Remove clear command from command summary for `MAIN_SELECTED_MODE`.
Add some info to Next and PreviousCard command
=> Add and fix UG bugs

docs/DeveloperGuide.md, docs/UserGuide.md, docs/diagrams/AddDeckActivityDiagram.puml, docs/diagrams/NextCardReviewActivityDiagram.puml, docs/diagrams/TypicalReviewActivityDiagram.puml, docs/index.md, src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/ExitCommand.java, src/main/java/seedu/address/model/ModelManager.java
=> Update all instances of PowerCard to PowerCards

docs/DeveloperGuide.md
Update manual testing for the main mode when a deck is selected.
=> Update manual testing on DG

docs/DeveloperGuide.md
=> Update manual testing commands on DG

src/main/resources/view/CardElement.fxml, src/main/resources/view/DeckName.fxml, src/main/resources/view/MainWindow.fxml, src/main/resources/view/NavGuide.fxml, src/main/resources/view/ReviewCard.fxml
=> Remove JavaFX warnings

src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/ui/MainWindow.java
=> Clear resets any filter on deck

docs/DeveloperGuide.md
=> Update Effort on DG

docs/DeveloperGuide.md
Improved the format of DG 
No new context added
=> Improved DG
